Name - Aditya Kothari

Roll no. - I028

Batch  - B1

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

Task 1:

 Perform basic operations using Tensorflow (Defining constants, variables, concatenation, add, multiply, reduce mean, reduce sum)

In [11]:
#Defining constants and variables and concatinating them
A = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
B = tf.Variable([[5, 6, 7, 8], [9, 10, 11, 12]])

AB_concat = tf.concat([A, B], axis=1)
print(AB_concat.numpy())


#Adding, multiplying
print("\nOn Adding:\n")
AB_add = tf.add(A, B)
print(AB_add.numpy())

print("\nOn Multiplying:\n")
AB_multiply = tf.multiply(A, B)
print(AB_multiply.numpy())


[[ 1  2  3  4  5  6  7  8]
 [ 5  6  7  8  9 10 11 12]]

On Adding:

[[ 6  8 10 12]
 [14 16 18 20]]

On Multiplying:

[[ 5 12 21 32]
 [45 60 77 96]]


In [12]:
#Reduce Mean
AB_reduce_mean = tf.reduce_mean(A)
print(AB_reduce_mean.numpy())

4


In [13]:
#Reduce Mean with axis = 0
AB_reduce_mean = tf.reduce_mean(A, 0)
print(AB_reduce_mean.numpy())

[3 4 5 6]


In [14]:
#Reduce sum
AB_reduce_mean = tf.reduce_sum(A)
print(AB_reduce_mean.numpy())

36


In [15]:
#Reduce sum with axis = 0
AB_reduce_mean = tf.reduce_sum(A, 0)
print(AB_reduce_mean.numpy())

[ 6  8 10 12]


Task 2:

Perform linear algebra operations using Tensorflow (transpose, matrix multiplication, elementwise multiplication, determinant)

In [16]:
#Transposing matrix A
A_transpose = tf.transpose(A)
print(A_transpose.numpy())

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [17]:
#Matrix multiplication
features = tf.constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = tf.constant([[1000], [150]])
AB_multiplication = tf.linalg.matmul(features, params)
print(AB_multiplication.numpy())

[[ 5600]
 [ 5900]
 [10550]
 [ 6550]]


In [18]:
A1 = tf.constant([1, 2, 3, 4])
A23 = tf.constant([[1, 2, 3], [1, 6, 4]])

#Define B1 and B23 to have the correct shape
B1 = tf.ones_like(A1)
B23 = tf.ones_like(A23)

#Perform element-wise multiplication
C1 = tf.multiply(A1, B1)
C23 = tf.multiply(A23, B23)

#Print the tensors C1 and C23
print('C1: {}'.format(C1.numpy()))
print('C23: {}'.format(C23.numpy()))

C1: [1 2 3 4]
C23: [[1 2 3]
 [1 6 4]]


In [19]:
#Element wise multiplication
B1 = tf.ones_like(features)
AB_element_wise = tf.multiply(features, B1)
print(AB_element_wise.numpy())

[[ 2 24]
 [ 2 26]
 [ 2 57]
 [ 1 37]]


In [20]:
#Determinant
A = tf.constant([[1, 2], [5, 6]], dtype=tf.float32)
A_determinant = tf.cast(A, dtype=tf.float32)
A_determinant = tf.linalg.det(A)
print(A_determinant.numpy())

-4.0


Task 3:

Perform derivative and higher order derivative for function f(x) = x^3 using gradient tape of Tensorflow

In [21]:
#Perform derivative and higher order derivative for function f(x) = x^3 using gradient tape of Tensorflow
x = tf.Variable(4.0)

with tf.GradientTape(persistent=True) as tape:
  y = x**3
  dy_dx = tape.gradient(y, x)
  dy_dx_2 = tape.gradient(dy_dx, x)
print("First order derivative: ", dy_dx.numpy())
print("Second order derivative: ", dy_dx_2.numpy())


First order derivative:  48.0
Second order derivative:  24.0


Task 4:

Compute WX+b using Tensorflow where W, X,  and b are drawn from a random normal distribution. W is of shape (4, 3), X is (3,1) and b is (4,1)

In [22]:
W = tf.Variable(tf.random.normal((4, 3)))
X = tf.Variable(tf.random.normal((3, 1)))
B = tf.Variable(tf.random.normal((4, 1)))

print((tf.matmul(W, X) + B.numpy()))

tf.Tensor(
[[-1.1527684]
 [-2.1059577]
 [-0.3005672]
 [-0.7499763]], shape=(4, 1), dtype=float32)


Task 5:

Compute Gradient of sigmoid function using Tensor flow

In [23]:
x = tf.constant(0.0)
with tf.GradientTape(persistent=True) as tape:
  tape.watch(x)
  y = tf.nn.sigmoid(x)

grad = tape.gradient(y, x) # dy/dx
print(grad.numpy())

0.25


Task 6:

Identify two research papers based on deep learning. State for which application they have used deep learning. (Cite the papers)

1. **ImageNet Classification with Deep Convolutional Neural Networks**

**Authors:** Alex Krizhevsky, Ilya Sutskever, Geoffrey E. Hinton

**Application:** This paper introduced the concept of using deep convolutional neural networks (CNNs) for image classification tasks. It proposed the architecture known as "AlexNet," which achieved a breakthrough in the ImageNet Large Scale Visual Recognition Challenge in 2012, significantly advancing the field of image classification using deep learning.


---



2. **Attention Is All You Need**

**Authors:** Ashish Vaswani, Noam Shazeer, Niki Parmar, et al.

**Application:** This paper introduced the Transformer architecture, which leverages self-attention mechanisms to process sequences in parallel, making it highly effective for tasks involving sequential data, such as machine translation, text generation, and language understanding. The Transformer architecture marked a significant shift in natural language processing and has also found applications in other domains.
Paper: Attention Is All You Need